defaults:
  - base_config
  - dataset: default        # Default dataset configuration
  - model: unet            # Default model configuration

# Base training configuration

batch_size: 16
lr: 1e-2
num_epochs: 100
ml_flow_uri: "file://${hydra:runtime.cwd}/runs"
model_dir: ${hydra:runtime.cwd}/models
model_tag: "unet.pt"
visualize_model: true
plot_3d: true
