defaults:
  - base_config
  - dataset: default        # Default dataset configuration
  - model: unet            # Default model configuration

# Base training configuration

batch_size: 4
lr: 1e-3
num_epochs: 20
ml_flow_uri: "file://${hydra:runtime.cwd}/runs"
model_dir: ${hydra:runtime.cwd}/models
model_tag: "unet.pt"
